mrc-ide/monty

DESCRIPTION, R/model.R, R/sampler-random-walk.R, man/mcstate_model.Rd, man/mcstate_model_properties.Rd, man/mcstate_sampler_random_walk.Rd, tests/testthat/helper-mcstate2.R, tests/testthat/test-model.R, tests/testthat/test-sampler-random-walk.R
Note that this PR pulls in `dust` for now, to use in the tests.  That is probably not what we really want because dust is going to depend on mcstate for its rng calls!  Once we work out what we need, I'll hand-write a version of this model that does the job, but this setup should be ok for a while (probably until we know enough to write dust2, really).
I've left a little placeholder in around *getting* rng state from the model; that is going to interact with restartable mcmc in ways that are going to require some care I think.
There's no actual testing in the stochastic model + random walk; however, this constitutes "particle MCMC" which is cool.  There are a couple of small features we will likely add there later based the covid work:
* the ability to rerun the likelihood every so often …
=> Support for stochastic models

R/runner.R, R/sample.R, R/sampler-hmc.R, man/mcstate_sample.Rd, tests/testthat/test-sample.R, tests/testthat/test-sampler-hmc.R, tests/testthat/test-sampler-random-walk.R
This PR drops the initial point from the chain.  It complicates a few things (in implementing support for observers most recently) to retain it so I've dropped it.  Ed indicated that it was useful to know where we've come from so I have retained an `initial` field which holds initial conditions
=> Don't include initial point in chain

R/runner.R, R/sample.R, R/sampler-adaptive.R, R/sampler-hmc.R, R/sampler-random-walk.R, tests/testthat/test-sample.R, tests/testthat/test-sampler-adaptive.R, tests/testthat/test-sampler-hmc.R, tests/testthat/test-sampler-random-walk.R
This PR tidies up how samplers are started:
* e95d9a0 is a small fix that does something I keep wanting - we leave it up to the sampler to return the initial state (so given pars, return a list with pars/density). This is going to be nice once we get observer support and for nested models (with likelihoods that can be separated into different pieces)
* everything else is a larger set of changes that allows saving/loading of internal state from a sampler
After running a chain, in addition to dumping out the rng state we also dump out the sampler state (this is empty for the random walk sampler and just the debug information for the HMC sampler, but for the adaptive sampler in #15 it will be fairly complex).  We pass that back in to `mcstate_run_chain` (along with the rng state) when …
=> Improvements to sampler initialisation and restart

R/arrays.R, R/util.R, tests/testthat/helper-mcstate2.R, tests/testthat/test-arrays.R, tests/testthat/test-util.R
This PR stands in the way of parameter refactoring, and pulls in (with light modification) the array utilities from mcstate.  These make doing some operations with arrays a little easier, but they are a bit of a handful tbh.  We will likely export these later (hence the fairly thorough error handling) but for now I just want them to be able to bind together and expand some arrays
* `array_bind`- I want this for binding arrays together as layers when combining chains (adding a dimension), and end-on-end when appending chains (lengthening an existing dimension)
* `array_reshape` - expands a dimension of an array to a different shape (used to convert a 2d array into a 3d array for example)
Original code here: https://github.com/mrc-ide/mcstate/blob/master/R/arrays.R
See …
=> Import array utilities

R/sampler-adaptive.R, inst/WORDLIST, man/mcstate_sampler_adaptive.Rd, vignettes/samplers.Rmd
This PR pulls in @MJomaba's banana Rmd doc into the nascent "samplers" vignette. More can be added later!
I've restructured the original a bit to make it a bit faster.  It does make me think that optionally being able to sample many points, or compute many densities, might be nicer.  But it will definitely complicate the interface with unexpected moves between vector and matrix return values.
Closes #11
=> Add banana doc

R/model.R, R/runner.R, R/sample.R, R/sampler-adaptive.R, R/sampler-helpers.R, R/sampler-hmc.R, R/sampler-random-walk.R, man/mcstate_model.Rd, man/mcstate_model_properties.Rd, tests/testthat/helper-mcstate2.R, tests/testthat/test-model.R, tests/testthat/test-sample.R, tests/testthat/test-sampler-adaptive.R, tests/testthat/test-sampler-hmc.R
More bits found while trying to get ready to run observers.
This PR will allow stochastic models to be correctly restarted. This requires that we pull the rng state from the model at the end of running the chain and saving that into the restart data.  This ended up being quite fiddly (81340df) but is not actually a lot of code.  The test in 903e808 failed before this change because the model rng was re-seeded from the chain rng, which is actually pretty terrible as then we reuse a bunch of the same rng chain as before!
With this in, I've made the decision to simplify how model rng setting needs to happen; we now require a raw vector (see the doc change).  This then results in a nice symmetry with getting the rng state at the end of the simulation.
I've then had to change the example a …
=> Correctly restart stochastic models

R/runner.R, R/sample.R, man/mcstate_sample_continue.Rd, tests/testthat/test-sample.R
Small missing feature for the (doomed) parallel runner; continue chains that were started in parallel.
I've folded in an additional small feature which allows the runner to be changed at restart.
=> Allow continuing parallel chains

R/dsl-parse.R, R/dsl.R, tests/testthat/test-dsl-parse.R
This PR adds support for parsing the basic DSL, with much more validation to come (and of course, generation).
The DSL so far is an ordered sequence of either assignments with `<-` or distributional statements with `~`; this will feel **very** familiar to the arguments to `quap` in Statistical Rethinking, and that is not a cooincidence.
So the priors corresponding to the regression model from Ch4 that we've been pondering:
```r
a ~ Normal(178, 20)
b ~ Normal(0, 1) # LogNormal distribution not actually supported yet
sigma ~ Uniform(0, 1)
```
The user can assign
```r
a_mean <- 178
a <- Normal(a_mean, 20)
```
and expressions can be used as arguments.  Order matters, so we disallow
```r
a ~ Normal(b, 1)
b <- 10
```
(this is in contrast to odin).
The error handling in the above is quite nice …
=> Parse basic dsl

.Rbuildignore, R/dsl-distributions.R, R/dsl-generate.R, R/dsl-parse.R, R/dsl.R, R/util.R, mcstate2.Rproj, tests/testthat/test-dsl-distributions.R, tests/testthat/test-dsl-generate.R, tests/testthat/test-dsl-parse.R, tests/testthat/test-dsl.R, tests/testthat/test-util.R
This PR implements two features that can be separated, but were developed together.  If you would prefer to review them separately I can easily chop them back apart.
First, we add support for some basic distribution objects (e.g., the Exponential distribution or the Normal distribution).  This is mostly just a list with parameters of the distributions and density/sampling functions.  There are two wrinkles here though:
* the domain is not trivial, because for Uniform the practical domain is [`min`, `max`] and not (`-Inf`, `Inf`).  This means that we need the parameters before we can compute the range and that's going to require some thought.  So for now we don't know the domains, which will restrict use with HMC but that's fine as we also don't support differentiation!
* some …
=> Better handling of distributions + basic density generation

.Rbuildignore, R/progress.R, R/runner.R, R/util_assert.R, man/mcstate_runner_serial.Rd, mcstate2.Rproj, tests/testthat/setup.R, tests/testthat/test-progress.R, tests/testthat/test-util-assert.R
Create a fairly informative progress bar that shows how each chain, and the overall sampling process, is going.  I've got a small set of vertical bars (one per chain) and a big bar that shows the total sampling progress.  The underlying progress printing machinery will be repurposable for the callr-based parallel runner similar to what we use in mcstate1 at which point it will look slightly more interesting.  I think this is better than one bar per chain in order as the thing that the user cares about is "when is this going to end" and the bar and ETA here capture that more closely.
Code to experiment:
```{r}
options(cli.progress_show_after = 0)
set.seed(1)
m <- ex_dust_sir()
vcv <- matrix(c(0.0006405, 0.0005628, 0.0005628, 0.0006641), 2, 2)
sampler <- mcstate_sampler_random_walk(vcv = …
```
=> Add support for progress bars

inst/include/mcstate/random/prng.hpp
This PR tidies up a small issue that bugged me, in that `export_state` does not modify the RNG so it should be a `const` method.  Later we might make this a bit more flexible too
=> Make export_state a const method

R/model.R, man/mcstate_model.Rd, tests/testthat/test-model.R
Less explicit way of specifying the domain.  With this, the user can provide explicit parameter domains for a subset of model parameters and the remainder are assumed to be valid over `(-Inf, Inf)`
=> More flexible domain

R/dsl-generate.R, tests/testthat/test-dsl.R
So, I thought I'd done more of this but it turns out that I have not done so.
This PR generates `direct_sample` capability for a model, following the same logic as used to generate the density; that is, we work down the statements and evaluate expressions in turn.  The difference is that when computing density when we hit:
```
a ~ Normal(0, 1)
```
we'd save into our final density the result of the density of `density(Normal(a, 0, 1))`, here we need to save into a parameter vector a draw from `Normal(0, 1)`.
To make this easier to implement I've made some changes to the code generation:
* we now use parameter unpacking via the packer; we then work in the "scope" created by that list.  This means we unpack into a list and any assignments would assign into that same list, removing the use of …
=> Generate sample functions from dsl

vignettes/dsl.Rmd
~Merge after #44, as we use the domain bits from there~
This is just a start, really
=> DSL speculative docs

R/cpp11.R, R/dsl-differentiate-expr.R, R/dsl-distributions.R, R/rng.R, inst/include/mcstate/random/beta.hpp, inst/include/mcstate/random/density.hpp, inst/include/mcstate/random/exponential.hpp, inst/include/mcstate/random/gamma.hpp, inst/include/mcstate/random/nbinomial.hpp, inst/include/mcstate/random/random.hpp, man/mcstate_rng.Rd, src/cpp11.cpp, src/random.cpp, tests/testthat/helper-mcstate2.R, tests/testthat/test-dsl-distributions.R, tests/testthat/test-rng.R
Merge after #51, contains those commits.
Note that this PR will break both dust2 and mcstate2 as they make calls to distributions referenced here, but the fix is easy.
There are more distributions to add - negative binomial and beta binomial are pretty high up - but this fills in some important gaps.
We're also getting to the point where I need to start on overhauling the rng interface generally - the `mcstate_rng` bit was never really meant to be used like this, unfortunately, and we simply don't expose the densities for testing at all.  But a job for a future PR I think
=> Expand distribution support

.github/workflows/check-version.yml, .github/workflows/pkgdown.yaml, DESCRIPTION, _pkgdown.yml, scripts/bump_version, scripts/check_version
We're at the point now where this would be useful I think. See the failing check on the first commit before I updated the version number (with `./scripts/bump_version`).
I've also set up the pages build to ignore history and fix the pkgdown url
=> Import version check/update scripts from orderly2

DESCRIPTION, R/packer.R, man/mcstate_packer.Rd, tests/testthat/test-packer.R
This will be useful in dust's code; see https://github.com/mrc-ide/dust2/pull/53/files#r1719553938 for details
=> Allow scalars to be passed as rank-0 arrays

DESCRIPTION, R/packer.R, R/util.R, man/monty_packer.Rd, tests/testthat/test-packer.R
The first commit (7aa5a234c22d04cabaa71f2781be6826b393ff7a) fixes a small bug that I noticed when working with dust to unpack output from dust models, where we were treating "scalars" created via the `array` argument slightly differently to those created via the `scalar` argument.
The next couple of commits, and the bulk of this PR fixes a problem I noticed working with this, where we simply don't support packing multidimensional inputs.  I don't think we'll do this very often but it felt like the current implementation was not good enough.  This is surprisingly horrible to do, and I think that's reflected in the error messages and help files.   This is something I feel we'll improve on over time.
=> Packer improvements

DESCRIPTION, R/sample-manual.R, _pkgdown.yml, man/monty_sample_manual_collect.Rd, man/monty_sample_manual_prepare_continue.Rd, vignettes/monty.Rmd, vignettes/samplers.Rmd
* missing title tags in the reference
* we would benefit from section headers in the article list
=> Fix doc rendering issues

DESCRIPTION, R/runner-callr.R, R/runner-simultaneous.R, R/runner.R, R/sample-manual.R, R/sample.R, R/sampler-adaptive.R, R/sampler-helpers.R, R/sampler-hmc.R, R/sampler-nested-adaptive.R, R/sampler-nested-random-walk.R, R/sampler-random-walk.R, man/monty_sample.Rd, man/monty_sample_manual_prepare.Rd, tests/testthat/test-runner-simultaneous.R, tests/testthat/test-sample.R, tests/testthat/test-sampler-nested-adaptive.R, tests/testthat/test-sampler-nested-random-walk.R, tests/testthat/test-sampler-random-walk.R
We are going to try a new approach in a follow-on PR
=> Drop observers from monty

DESCRIPTION, R/packer.R
More on packers I am afraid, this time just a tidyup (notice no changes in the tests).  I need this in order to start the multiparameter  packers.
We have an argument of scalar and array, and this PR makes that simply sugar for the user.  Internally we treat everything identically.  If you look at some of the deleted bits you can see we were doing this already really.
=> Drop internal use of 'scalar' in packers

DESCRIPTION, R/cpp11.R, R/rng2.R, src/cpp11.cpp, src/random2.cpp, tests/testthat/helper-monty.R, tests/testthat/helper-sir-filter.R, tests/testthat/test-combine.R, tests/testthat/test-sample.R, tests/testthat/test-sampler-adaptive.R, tests/testthat/test-sampler-hmc.R, tests/testthat/test-sampler-random-walk.R
This PR removes `dust` as a dependency and starts the exploration of a proper rng interface.  There's quite a bit in here as a result.  But the main thing that we're **trying** to do is to build a well-behaved stochastic model that can eventually unblock #68.  I don't think that this has everything (you need grouped structure too, right @edknock?) but this gets us most of the way.
The `monty_rng` interface is not suitable for creating models because we can't use the streams in the same way as we do from dust.  If we have `n` values in `size` and `prob` and `n` streams in `rng_state` I want to be able to do `Binomial(size, prob, rng_state)` and have the first stream use the first size and prob, the second stream use the second etc.  This is not implemented in `monty_rng` and this means we …
=> Add native SIR filter example

DESCRIPTION, Makefile, R/runner-callr.R, R/runner-simultaneous.R, R/runner.R, R/sample-manual.R, R/sample.R, man/monty_sample.Rd, man/monty_sample_manual_prepare.Rd, tests/testthat/test-sample-manual.R, tests/testthat/test-sample.R
This PR allows thinning while the chain runs; this is primarily for cases where the observer will produce a lot of data.  To keep the general idea of the chain continuation working, the thinning rate cannot be changed after starting and you can only burnin the initial bit.  I think that later we might want to allow "continue but don't append" so that these things can be modified (same with things like changing the proposal)
=> Allow chain thinning/burnin while running

DESCRIPTION, R/sample-manual.R, R/sample.R, man/monty_sample_continue.Rd, man/monty_sample_manual_collect.Rd, tests/testthat/test-sample-manual.R, tests/testthat/test-sample.R
Sometimes we'll want to a continue a chain but ignore the previous inputs (e.g., we can see that the previous chain has a massive bit of burnin and is not stationary).  This PR adds an arg to make this easy.
Another similar thing we don't have yet but which would be useful is one to convert samples into sensible input for new initial conditions and a vcv, possibly for a different number of chains; that is not done here
=> Allow continuing chain without appending

DESCRIPTION, R/progress.R, R/runner-callr.R, R/runner-simultaneous.R, R/runner.R, R/sample-manual.R, R/util.R, man/monty_runner_callr.Rd, man/monty_runner_serial.Rd, man/monty_runner_simultaneous.Rd, man/monty_sample_manual_run.Rd, tests/testthat/setup.R, tests/testthat/test-progress.R
A nice test case from Ed:
```
prior <- monty::monty_dsl({
beta ~ Exponential(mean = 0.3)
gamma ~ Exponential(mean = 0.1)
})
sir <- dust2::dust_example("sir")
data <- data.frame(cases = 3:22,
time = 1:20)
filter <- dust2::dust_filter_create(sir, 0, data, n_particles = 200)
sir_packer <- monty::monty_packer(c("beta", "gamma"), fixed = list(I0 = 5))
likelihood <- dust2::dust_likelihood_monty(filter, sir_packer)
posterior <- prior + likelihood
sampler <- monty::monty_sampler_random_walk(diag(2) * 0.02)
pars <- list(beta = 0.3, gamma = 0.1, I0 = 5)
samples <- monty::monty_sample(posterior, sampler, 1000,
initial = sir_packer$pack(pars),
n_chains = 4)
```
Run this and cancel the progress run half way through  (Ctrl-C/Esc on Rstudio) then run the sampling again.  you end up with something like: …
=> Proper closing of progress bars on failure

DESCRIPTION, R/combine.R, R/dsl-generate.R, R/model.R, man/monty_model_properties.Rd, tests/testthat/test-combine.R, tests/testthat/test-dsl.R, tests/testthat/test-model.R
Two somewhat related features:
* DSL models now support (crudely) handling multiple parameters (a matrix of parameters yielding a vector of densities)
* We can propagate the `allow_multiple_parameters` property when combining models
=> Allow multiple parameters to dsl models

DESCRIPTION, R/packer-grouped.R, R/packer.R, tests/testthat/test-packer-grouped.R
Discussed with @edknock, this should actually solve the general case pretty well
=> Allow process for grouped packers

DESCRIPTION, R/sample.R, man/monty_sample.Rd, man/monty_sample_manual_prepare.Rd, tests/testthat/test-sample.R
This makes picking up after we left off much easier, and also allows the results of a single chain to be used to create starting points for the next chain.  A third way of continuing chains (after continue, continue with `append = FALSE`) but all 3 have their uses I think.
=> Allow using previous samples as initial conditions

DESCRIPTION, R/dsl-differentiate-expr.R, tests/testthat/test-dsl-differentiation.R
Spotted doing odin work, small PR there to fix effects of this too (https://github.com/mrc-ide/odin2/pull/106)
=> Don't use parens in uminus on prefix function

DESCRIPTION, R/runner-simultaneous.R, R/sampler-random-walk.R, tests/testthat/test-sample-manual.R, tests/testthat/test-sampler-hmc.R, tests/testthat/test-sampler-random-walk.R
This gets very close to known issues around stateful samplers, but this workaround should be ok for now.
=> Allow manually sampled chains to be restarted

DESCRIPTION, inst/include/monty/random/negative_binomial.hpp
`R_FINITE` is not available without using R's headers, and should not be used in this context
=> Don't use R macro

DESCRIPTION, inst/include/monty/random/density.hpp
Incorrect use of `^` replaced by `monty::math::pow`
=> Fix cauchy density

DESCRIPTION, R/cpp11.R, R/random.R, man/monty_random_normal.Rd, src/cpp11.cpp, src/random.cpp, tests/testthat/test-rng.R
This ports **most** tests over.
* multinomial tests will require another PR, as the interface there is quite different (multinomial draws take vector args and return vector values)
* the pointer bits still remain, but I might remove that
* the comparison tests with the new interface remain for now
This PR allows @edknock to get the tests set up for Weibull and LogNormal though
=> Port tests to new interface

DESCRIPTION, R/model.R, tests/testthat/_snaps/sample-manual.md, tests/testthat/test-combine.R, tests/testthat/test-example.R, tests/testthat/test-model.R, tests/testthat/test-sample-manual.R
There are still more to fix:
* the legacy rng ones will naturally go away in a couple of PRs
* the density and numeric ones require us to expose that interface
But this PR fixes some of the easy missing bits
=> Fix coverage holes

DESCRIPTION, R/cpp11.R, R/random.R, inst/include/monty/random/multinomial.hpp, src/cpp11.cpp, src/random.cpp, tests/testthat/test-rng.R
One of the last bits to move over, after this we can start removing the old interface I think
=> Port multinomial to new rng interface

DESCRIPTION, R/progress.R, tests/testthat/test-progress.R
When things don't change that often it looks like things have stalled, a progress bar helps with that.  This PR uses the cli progress bar to add a simple spinner at the start of the progress; I think we had this in mcstate?
=> Add spinner to progress bar

DESCRIPTION, R/random.R, _pkgdown.yml, inst/WORDLIST, man/monty_rng_create.Rd, vignettes/migration.Rmd
In the effort that the perfect not be the enemy of the good, here's a start on this, we can add more later.
=> Start on migration vignette

DESCRIPTION, R/sample-manual.R, tests/testthat/test-sample-manual.R
Reported by @thomrawson, see "odin etc" Teams channel.
This PR fixes data saved as part of a restart when running chains manually; we were incorrectly saving the model and sampler.  A test is added which compares against the non-manual version
=> Fix restarting restarted chains, run manually

DESCRIPTION, R/dsl-differentiate-expr.R, tests/testthat/test-dsl-differentiation.R
Some duplication of code from odin here, I've moved that within `maths` so that we can reuse it easily in odin.  Tests have been copied over too.
This PR includes support for differentiating array expressions.  These are quite hard to think about.
When we talk about differentiating with respect to `x` where `x` is an array, we seek to create an object with the same dimensions as `x`.  So if `x` is a vector then `d/dx(expr)` is a vector with the derivatives of `(x[1], x[2], ..., x[n])`.  Similarly if `x` is a matrix then `d/dx(expr)` is a matrix where element `(i, j)` is the derivative of `expr` with respect to `x[i, j]` and so on.
Array indexing is therefore pretty easy.  The derivative with respect to `x[...]` is 1 if we have a derivative of `x` at *exactly the same index* and 0 …
=> Support for differentiation through arrays

DESCRIPTION, R/dsl-distributions.R
Using `TruncatedNormal` in the DSL was throwing an error e.g.
```
m <- monty::monty_dsl({
X ~ TruncatedNormal(mean = 5, sd = 1, min = 0, max = Inf)
},
gradient = FALSE)
```
resulted in
```
Error in (function (min, max)  : unused arguments (0, Inf)
```
This was because the domain function for `TruncatedNormal` had parameters `min, max` when of course it needed `mean, sd, min, max`!
=> fix domain issue for truncated normal

DESCRIPTION, R/model-function.R, R/packer.R, man/monty_model_function.Rd, man/monty_packer.Rd, tests/testthat/test-model-function.R, tests/testthat/test-packer.R
As seen in #137, our assumptions around how packers and multiple parameters don't hold here. We need to assume that the model function can cope with this, and so we intercept the packer before it would fail and inject the fixed parameters into the model function instead.
=> Better behaviour of packers, model functions and multiple parameters

DESCRIPTION, R/model-function.R, man/monty_model_function.Rd, tests/testthat/test-model-function.R
* `monty_model_function` does not expand the domain
* `call` was not being passed through to the validators, throwing an error while throwing an error
=> Fix two bugs found by Debbie

DESCRIPTION, inst/include/monty/random/density.hpp
I was trying to pass a `NaN` through an integer parameter and it went badly.  With this change a `NaN` comes out the calculation, which is expected.  In future we might want to specially short cut this, and we might then also want to consider what to do in the case of non-integer values for integral distributions (@edknock - I'm not sure which of these are really valid, or which we might *want* to be valid to support the deterministic model).
This supports https://github.com/mrc-ide/odin2/pull/151 and is required to make the integration test pass
=> Use real type everywhere in density calculation

DESCRIPTION, R/dsl-adjoint.R, inst/include/monty/random/density.hpp, tests/testthat/test-dsl.R
Reported by Keith over Teams.
Two separate bugs here - one is that we don't have a `density` expression for `TruncatedNormal`; arguably we should because it's not that hard to write out really, but it's also useful to handle the case where the density is not present gracefully so this fix is still useful. We already have a "can't create adjoint model" path, which I've exploited here by raising an error that is caught by the adjoint construction, converting to a warning by default and an error where the user says that they really want a gradient.
See this in action with Keith's original report code:
```
prior <- monty::monty_dsl({
beta ~ TruncatedNormal(mean = 0.2, sd = 0.1, min = 0.05, max = 0.5)
})
```
and see what happens with the `gradient` argument to `monty_dsl`
The other error is …
=> Fix issues with truncated normal

DESCRIPTION, inst/include/monty/random/binomial.hpp, tests/testthat/test-rng.R
As reported by Neil on Teams, this restores the short-cut path available on odin.dust, and is reasonable with the usual R-ish interpretations of missing data (changing the value of the `NA` will not change the answer).
=> More relaxed binomial check

R/arrays.R, R/runner-callr.R, R/runner-simultaneous.R, R/runner.R, R/sample-manual.R, R/sample.R, R/sampler-adaptive.R, R/sampler-hmc.R, R/sampler-random-walk.R, R/sampler.R, R/util.R, man/monty_sampler2.Rd, man/monty_sampler_adaptive.Rd, tests/testthat/helper-monty.R, tests/testthat/helper-sampler.R, tests/testthat/test-sample.R, tests/testthat/test-sampler-adaptive.R, tests/testthat/test-sampler-hmc.R, tests/testthat/test-sampler-random-walk.R, tests/testthat/test-sampler.R
All the samplers are now v2 samplers so remove old support.  This one is mechanical at least!
Merge after #162, contains those commits
=> Drop support for legacy samplers

DESCRIPTION, R/util.R, tests/testthat/test-util.R
As discussed on Teams, there are some matrices where our eigenvalue check (all eigenvalues are nonzero, to machine precision) but are not suitable for use as a vcv because they are rank deficient.  This would not happen if we had infinite precision, because the rank deficiency requires that an eigenvalue is zero (citation: someone on SO - https://math.stackexchange.com/questions/1524444/connection-between-rank-and-positive-definiteness). 
The example here is a subset of the larger matrix that Keith was working with, which shows the same pathology. It is *very* close to failing the eigenvalue test
=> Add stricter test for vcv

DESCRIPTION, R/example.R, R/sampler-parallel-tempering.R, man/monty_example.Rd, man/monty_sampler_parallel_tempering.Rd, tests/testthat/test-example.R, tests/testthat/test-parallel-tempering.R
An example, though not terribly convincing at present (see below for an update though)
```
set.seed(1)
likelihood <- ex_mixture(5)
n_rungs <- 5
prior <- monty_dsl({
x ~ Normal(0, 10)
})
posterior <- likelihood + prior
sampler <- monty_sampler_parallel_tempering(
n_rungs = n_rungs,
sampler = monty_sampler_random_walk(vcv = matrix(0.1)))
res <- monty_sample(posterior, sampler, 500, n_chains = 4)
sampler2 <- monty_sampler_parallel_tempering(
beta = res$details$beta,
sampler = monty_sampler_random_walk(vcv = matrix(0.1)))
res2 <- monty_sample(posterior, sampler2, 500, n_chains = 4)
sampler3 <- monty_sampler_parallel_tempering(
beta = res2$details$beta,
sampler = monty_sampler_random_walk(vcv = matrix(0.1)))
res3 <- monty_sample(posterior, sampler2, 500, n_chains = 4)
```
This PR also includes …
=> Tune beta values in parallel tempering

DESCRIPTION, R/sampler-hmc.R, tests/testthat/test-parallel-tempering.R
This fixes an issue where currently `monty_sample_continue` works for HMC if `debug = FALSE` 
```
set.seed(1)
prior <- monty_dsl({
x1 ~ Normal(0, 2)
x2 ~ Normal(0, 2)
})
likelihood <- monty_example("mixture2d", k = 10, spread = 5)
posterior <- likelihood + prior
sampler1 <- monty_sampler_parallel_tempering(
n_rungs = 10,
sampler = monty_sampler_hmc(),
base = prior)
res1 <- monty_sample(posterior, sampler1, 500, n_chains = 3, initial = c(0, 0),
restartable = TRUE)
res1 <- monty_sample_continue(res1, 1000)
```
but not when `debug = TRUE`
```
sampler2 <- monty_sampler_parallel_tempering(
n_rungs = 10,
sampler = monty_sampler_hmc(debug = TRUE),
base = prior)
res2 <- monty_sample(posterior, sampler2, 500, n_chains = 3, initial = c(0, 0),
restartable = TRUE)
res2 <- monty_sample_continue(res2, …
```
=> Ensure monty_sample_continue works with HMC with debug on
